# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eV_V1G7vcpdNuXDhDeLqFgOvs6NKmauy
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/SampleSuperstore.csv")

ship_mode = df["Ship Mode"].to_numpy()
print(ship_mode)

segment =df["Segment"].to_numpy()
print(segment)

country =df["Country"].to_numpy()
print(country)

city =df["City"].to_numpy()
print(city)

state =df["City"].to_numpy()
print(state)

postal_code=df["Postal Code"].to_numpy()
print(postal_code)

region =df["Region"].to_numpy()
print(region)

category =df["Category"].to_numpy()
print(category)

sub_category = df["Sub-Category"].to_numpy()
print(sub_category)

sales=df["Sales"].to_numpy()
print(sales)

quantity=df["Quantity"].to_numpy()
print(quantity)

discount =df["Discount"].to_numpy()
print(discount)

profit=df["Profit"].to_numpy()
print(profit)

print("The sales dataset has been loaded, and relevant columns have been converted into NumPy arrays:")
if 'df' in locals():
    numpy_array_names = [
        "ship_mode", "segment", "country", "city", "state", "postal_code",
        "region", "category", "sub_category", "sales", "quantity", "discount", "profit"
    ]

    for name in numpy_array_names:
        if name in locals():
            arr = locals()[name]
            print(f"- '{name}' (shape: {arr.shape}, dtype: {arr.dtype})")
        else:
            print(f"- '{name}' was not found or not yet defined.")
else:
    print("The DataFrame 'df' was not found. Please ensure the dataset is loaded.")

total_sales = np.sum(sales)
average_sales = np.mean(sales)

print(f"Total Sales: {total_sales:.2f}")
print(f"Average Sales: {average_sales:.2f}")



# Extract the first 5 sales records
first_five_sales = sales[:5]
print(f"First 5 sales records: {first_five_sales}")

# Extract sales records from index 10 to 14 (inclusive)
sales_10_to_14 = sales[10:15]
print(f"Sales records from index 10 to 14: {sales_10_to_14}")

# Extract every 10th sales record
every_tenth_sales = sales[::1000]
print(f"Every 1000th sales record: {every_tenth_sales}")

# Extract sales records where sales are greater than 500
high_sales_records = sales[sales > 500]
print(f"Sales records greater than 500 (first 10 examples): {high_sales_records[:10]}")
print(f"Total count of sales records greater than 500: {len(high_sales_records)}")

mean_sales = np.mean(sales)
median_sales = np.median(sales)
variance_sales = np.var(sales)
std_dev_sales = np.std(sales)

print(f"Mean Sales: {mean_sales:.2f}")
print(f"Median Sales: {median_sales:.2f}")
print(f"Variance of Sales: {variance_sales:.2f}")
print(f"Standard Deviation of Sales: {std_dev_sales:.2f}")

unit_price_per_item = sales / quantity
revenue_per_item = unit_price_per_item * quantity

print(f"First 5 calculated Unit Prices per item: {unit_price_per_item[:5]}")
print(f"First 5 calculated Revenues per item (should be same as sales): {revenue_per_item[:5]}")

print(f"\nAre calculated revenues equal to the original sales array? {np.allclose(revenue_per_item, sales)}")

profit_margin = (profit / sales) * 100

print(f"First 10 calculated Profit Margins: {profit_margin[:10].round(2)}%")
print(f"Average Profit Margin across all sales: {np.mean(profit_margin).round(2)}%")

# Find sales where profit margin is negative (indicating a loss)
loss_making_sales_count = np.sum(profit_margin < 0)
print(f"Number of sales with a negative profit margin (loss): {loss_making_sales_count}")

"""### Sales Performance Interpretation

From the various NumPy operations we've performed, we can draw several insights into the sales data:

*   **Overall Sales Volume:** The `Total Sales` of `{total_sales:.2f}` indicates a substantial overall business activity. The `Average Sales` per transaction, `{average_sales:.2f}`, provides a baseline for individual transaction value.

*   **Sales Distribution (Central Tendency):**
    *   The `Mean Sales` (`{mean_sales:.2f}`) and `Median Sales` (`{median_sales:.2f}`) are quite close, suggesting that the sales data might have a somewhat symmetrical distribution, though the mean being slightly higher than the median could indicate a slight positive skew (a few high-value sales pulling the average up).

*   **Sales Variability (Spread):**
    *   The `Variance of Sales` (`{variance_sales:.2f}`) and `Standard Deviation of Sales` (`{std_dev_sales:.2f}`) are relatively large. This indicates significant variability in sales amounts between different transactions. There's a wide range from very small to very large sales.

*   **Profitability Analysis:**
    *   The `Average Profit Margin` (`{np.mean(profit_margin):.2f}%`) gives an overall picture of the business's profitability. A positive average is good, but the detailed profit margins can reveal more.
    *   The `Number of sales with a negative profit margin (loss)` (`{loss_making_sales_count}`) is a critical metric. It highlights that a portion of the sales are actually generating losses. This could be due to discounts, high product costs, or other factors, and warrants further investigation to improve profitability.

*   **Specific Sales Records:**
    *   We observed `high_sales_records` (sales greater than 500), indicating that while many sales might be smaller, there are a good number of high-value transactions contributing significantly to the total revenue.

In summary, the sales data shows a healthy overall volume but with considerable variability in individual transaction values and a notable number of loss-making sales. Further analysis could delve into what drives high-value sales versus low-value sales, and particularly what causes negative profit margins.
"""